### ISSUE TITLE
PyenvFinder.create raises when there are debug versions in PYENV_ROOT

### ISSUE THREAD

**Issue by immerrr** [sarugaku/pythonfinder#12]
This bug manifested itself for me via pipenv and was originally reported as pypa/pipenv#2964, but it was requested to reopen it here.

The problem is that pythonfinder is very careful about parsing python versions and very noisy if it cannot succeed. Here's a quick repro:

```
$ mkdir pipenv-temp; cd pipenv-temp
$ pyenv install 3.6.4
$ pyenv install 3.6.6 --debug
$ pipenv --python 3.6.4
```

Here's how a real case from my system looks like:

<details><summary>pyenv versions</summary>

```
immerrr@mmrcomp:~/pipenv-temp$ pyenv versions
* system (set by /home/immerrr/src/pyenv/version)
  3.6.4
  3.6.6
  3.6.6-debug
  3.7.0
```
</details>

And when I try to install a perfectly valid version of Python, it raises the following:

<details><summary>pipenv --python 3.6.4 (traceback)</summary>

```
immerrr@mmrcomp:~/pipenv-temp$ pipenv --verbose --python 3.6.4
Traceback (most recent call last):
  File "/home/immerrr/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/cli/command.py", line 203, in cli
    clear=state.clear,
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/core.py", line 561, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
    ensure_python(three=three, python=python)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 86, in find_python_version
    return self.system_path.find_python_version(
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 40, in system_path
    global_search=self.global_search,
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 305, in create
    global_search=global_search,
  File "<attrs generated init 86da6fe0111de9e514cb2e45cc4c2cdd5d1b77a5>", line 36, in __init__
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 101, in __attrs_post_init__
    self._setup_pyenv()
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 132, in _setup_pyenv
    self.pyenv_finder = PyenvFinder.create(root=PYENV_ROOT)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 52, in create
    return cls(root=root)
  File "<attrs generated init b7362d3ad3f81af215543f778c6ac52da8efc1bf>", line 6, in __init__
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 26, in get_versions
    version = PythonVersion.parse(p.name)
  File "/home/immerrr/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 110, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('3.6.6-debug')>
```

</details>

Without pipenv, the bug can be reproduced as follows ([courtesy of this comment](https://github.com/pypa/pipenv/issues/2964#issuecomment-428189536)):

```
from pythonfinder import Finder
finder = Finder(system=False, global_search=True)
finder.find_all_python_versions()
```

**Comment by techalchemy** [comment]
@rbcollins123 can you give me some sample output? that's horrible, also, good information to have

**Comment by keithly** [comment]
I have the same issue as @rbcollins123 . I have brew installed pyenv 1.2.7 on macOS Sierra. Here's the stacktrace I get when I run `pipenv install` with version 2018.10.9 

```
Traceback (most recent call last):
  File "/Users/myuser/.pyenv/versions/3.6.6/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/core.py", line 1695, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/core.py", line 561, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/core.py", line 484, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 86, in find_python_version
    return self.system_path.find_python_version(
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 40, in system_path
    global_search=self.global_search,
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 305, in create
    global_search=global_search,
  File "<attrs generated init bde0054ea6f8f56b755b8b6facd8b8699a25e504>", line 36, in __init__
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 101, in __attrs_post_init__
    self._setup_pyenv()
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 132, in _setup_pyenv
    self.pyenv_finder = PyenvFinder.create(root=PYENV_ROOT)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 52, in create
    return cls(root=root)
  File "<attrs generated init 5d89303a6785c97db0904a7da539ceea81ee5e9a>", line 6, in __init__
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 26, in get_versions
    version = PythonVersion.parse(p.name)
  File "/Users/myuser/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 110, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('a-pyenv-virtualenv-name')>
```

**Comment by rbcollins123** [comment]
Yep, @keithly beat me to it... my output is same. I came across it when using pipenv also.  I'm also on MacOS but pyenv is not brew installed, it's from the latest repo, but same outcome.

``` ✘  /tmp/test  pipenv --python 2.7.15 install
Traceback (most recent call last):
  File "/Users/rcollins/.pyenv/versions/3.7.0/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/cli/command.py", line 203, in cli
    clear=state.clear,
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/core.py", line 561, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/core.py", line 484, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 86, in find_python_version
    return self.system_path.find_python_version(
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 40, in system_path
    global_search=self.global_search,
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 305, in create
    global_search=global_search,
  File "<attrs generated init bde0054ea6f8f56b755b8b6facd8b8699a25e504>", line 36, in __init__
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 101, in __attrs_post_init__
    self._setup_pyenv()
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 132, in _setup_pyenv
    self.pyenv_finder = PyenvFinder.create(root=PYENV_ROOT)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 52, in create
    return cls(root=root)
  File "<attrs generated init 63e87fba6799f04aef9ccfcdb33f31398fff14d1>", line 6, in __init__
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 26, in get_versions
    version = PythonVersion.parse(p.name)
  File "/Users/rcollins/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 110, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('solarwinds')>```

**Comment by keithly** [comment]
I had pipenv installed under a pyenv version. When I uninstalled it and reinstalled with `brew install pipenv`, I didn't encounter this error. I guess I should've done that first, given that the pipenv home page says to brew install it on macOS.

**Comment by rbcollins123** [comment]
@keithly that doesn't seem to make any difference for me... i tried it both ways, with pipenv inside a pyenv python and also with it brew installed to the system interpreter.  Both routes result in the same failure

**Comment by rbcollins123** [comment]
@keithly try it again with `pipenv --python x.x.x install` and see if that fails in both cases for you.  I was always specifying a version, but just noticed if I start a new project with `pipenv install` and let it grab my default interpreter then it works fine

**Comment by rajaravivarma-r** [comment]
I can verify what rbcollins123 said. `pipenv install` in a new directory works just fine, but running the same in directory which was already initialized throws this error. I made sure that the virtualenv directory was not present. I even tried deleting the Pipfile and Pipfile.lock, but had no success.
```bash
Script started on Fri Oct 12 13:41:17 2018
[36m[~/Downloads/sitepoint/downloader][33m[0m : pipenv --rm
[31m[1mNo virtualenv has been created for this project yet![39m[22m
Aborted!
[36m[~/Downloads/sitepoint/downloader][33m[0m : pipenv install
Traceback (most recent call last):
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/core.py", line 1695, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/core.py", line 561, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/core.py", line 484, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 86, in find_python_version
    return self.system_path.find_python_version(
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 40, in system_path
    global_search=self.global_search,
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 305, in create
    global_search=global_search,
  File "<attrs generated init bde0054ea6f8f56b755b8b6facd8b8699a25e504>", line 36, in __init__
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 101, in __attrs_post_init__
    self._setup_pyenv()
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 132, in _setup_pyenv
    self.pyenv_finder = PyenvFinder.create(root=PYENV_ROOT)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 52, in create
    return cls(root=root)
  File "<attrs generated init d298aa38d447c6933ca797f906930fd0fc94afe8>", line 6, in __init__
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/pyenv.py", line 26, in get_versions
    version = PythonVersion.parse(p.name)
  File "/Users/rajaravivarma/.pyenv/versions/3.6.1/lib/python3.6/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 110, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('2.7.14_vim')>
[36m[~/Downloads/sitepoint/downloader][33m[0m : pyenv versions
  system
  2.7.14_vim
  2.7.9
  3.5.2
* 3.6.1 (set by /Users/rajaravivarma/Downloads/sitepoint/downloader/.python-version)
  3.6.6_vim
  3.7.0
[36m[~/Downloads/sitepoint/downloader][33m[0m : exit
exit

Script done on Fri Oct 12 13:41:58 2018
```

**Comment by techalchemy** [comment]
> I'll also add that pyenv-virtualenv puts symlinks to all virtualenvs in its /versions folder 

That is perfect, thanks for the info!
