### ISSUE TITLE
handle anaconda python (installed via pyenv)

### ISSUE THREAD

**Issue by AlJohri** [sarugaku/pythonfinder#20]
Fails to parse anaconda python installed via pyenv:

```
ValueError: Not a valid python version: <LegacyVersion('anaconda3-5.0.1')>
```

```
pipenv.vendor.pythonfinder.exceptions.InvalidPythonVersion: /Users/johria/.pyenv/versions/anaconda3-5.0.1/bin/anaconda is not a valid python path
```

See https://github.com/pypa/pipenv/issues/3044 for full traceback

**Comment by AlJohri** [comment]
looked into how this is implemented. this may be hard- can we at least default ignore_unsupported=True? without this pipenv entirely stops working if you have a invalid python installed

**Comment by AlJohri** [comment]
downgraded to pipenv `2018.7.1` for now

**Comment by AlJohri** [comment]
downgrading didn't work, ran into:

```
Installing requests...
Traceback (most recent call last):
  File "/Users/johria/.pyenv/versions/3.6.5/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/core.py", line 1971, in do_install
    pypi_mirror=pypi_mirror,
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/Users/johria/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
```

going to get rid of anaconda 😭

**Comment by techalchemy** [comment]
Hmmm I thought we did set that. That is a gross oversight and someone at continuum is going to be mad at me :(

You can use the full path I think

**Comment by AlJohri** [comment]
thanks for the quick fix @techalchemy! FWIW, full path did work earlier

**Comment by 302sk** [comment]
> Hmmm I thought we did set that. That is a gross oversight and someone at continuum is going to be mad at me :(
> 
> You can use the full path I think

What does full path mean?

**Comment by AlJohri** [comment]
@302sk `pipenv install --python=/Users/johria/.pyenv/versions/3.6.5/bin/python` or even `pipenv install --python=python`
