### ISSUE TITLE
asdf integration + handling shims?

### ISSUE THREAD

**Issue by AlJohri** [sarugaku/pythonfinder#35]
Hi, I recently switched over from pyenv to [asdf](https://github.com/asdf-vm/asdf) which is a cross-language replacement. Now I don't need `pyenv`, `rbenv`, `nodenv` all installed separately.

asdf uses python-build internally and installs everything into `~/.asdf/installs/python/`.

```bash
$ ls -1 ~/.asdf/installs/python/
2.7.15
3.6.7
3.7.1/
```

1. I was wondering if the pyenv integration was generic enough to be able to work with asdf as well

    The binaries are located at `~/.asdf/installs/python/3.7.1/bin/python` for example which I think is identical to pyenv.

    I was thinking if I set `PYENV_ROOT=$HOME/.asdf/installs/python/` it might work out?

2. I didn't have much success testing since the `shims` were getting in the way. I imagine this issue would be identical in pyenv or asdf. If my global version is set to 3.7.1, a shim would exist for pyhon3.6 and it would not be "active". For example, running the python3.6 shim while python3.7 is global would result in an error message like:

    ```bash
    $ asdf global python 3.7.1 # set global version to 3.7.1
    $ python3.6
    No such command in 3.7.1 of python
    ```

    So it has to go straight to PYENV_ROOT for the binaries and skip the shims. I think https://github.com/sarugaku/pythonfinder/issues/27 addesses this but wasn't sure if it would work generically enough for asdf as well.

    EDIT: Looks like the shim path for asdf is `$HOME/.asdf/shims` so setting PYENV_ROOT as I did above would not work.

Thanks!

**Comment by techalchemy** [comment]
To be honest I stopped using pyenv's shims because they break everything, but this should be relatively easy to port without pretending to have pyenv

IMO we should just add a specific adapter for `asdf` -- `pyenv` uses it's own finder type which gets registered [here](https://github.com/sarugaku/pythonfinder/blob/master/src/pythonfinder/models/path.py#L106) and we can just perform a similar check for `asdf`.  

That said, honestly it might work anyway because like I mentioned I ignore pyenv shims now anyway, they are terrible.

**Comment by techalchemy** [comment]
When I say it might work anyway, I mean `pyfinder --find 3.6` might work if you use the workaround you were trying

**Comment by uranusjr** [comment]
I’m thinking maybe we can introduce our own environment variable, so people can set to

```
PYTHONFINDER_ROOTS=~/.pyenv/versions:~/.asdf/installs/python
```

This would have a sensitive default as well. Does asdf expose an environment variable similar to `PYENV_ROOT`? It would be quite simple to interface if it does.

**Comment by AlJohri** [comment]
thanks @techalchemy, let me try that out

@uranusjr yes it does have an equivalent variable. the only thing different is where the pythons are located
- root: `PYENV_ROOT=$HOME/.pyenv` vs `ASDF_DATA_DIR=$HOME/.pyenv` ✅
- shims: `$PYENV_ROOT/shims` vs `$ASDF_DATA_DIR/shims`  ✅
- pythons: `$PYENV_ROOT/versions` vs `$ASDF_DATA_DIR/installs/python` ❌

**Comment by techalchemy** [comment]
PR is up, let me know if it works for you

**Comment by AlJohri** [comment]
let me give that a shot. in the mean time, just ran into this https://github.com/pypa/pipenv/issues/3214 while trying to install via pipenv

**Comment by AlJohri** [comment]
I got this error (which has to do with shims)

```
Traceback (most recent call last):
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/bin/pyfinder", line 11, in <module>
    load_entry_point('pythonfinder', 'console_scripts', 'pyfinder')()
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/cli.py", line 33, in cli
    versions = [v for v in finder.find_all_python_versions()]
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 121, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict")
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 53, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 419, in create
    for p in _path_objects
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 419, in <dictcomp>
    for p in _path_objects
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 539, in create
    _new = cls(**creation_args)
  File "<attrs generated init 118615c65267bfc1863cbf5e6f1d4854e12c3322>", line 20, in __init__
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 495, in get_pythons
    for path, entry in self.children.items():
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 469, in children
    for child_key, child_val in self._gen_children():
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 462, in _gen_children
    yield (child.as_posix(), PathEntry.create(path=child, **pass_args))
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 539, in create
    _new = cls(**creation_args)
  File "<attrs generated init 118615c65267bfc1863cbf5e6f1d4854e12c3322>", line 16, in __init__
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 485, in get_py_version
    py_version = PythonVersion.from_path(path=self, name=self.name)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/python.py", line 203, in from_path
    instance_dict = cls.parse(py_version)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/python.py", line 151, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('No such command in 3.7.1 2.7.15 of python')>
```

The error might be confusing because my global python is set to both `3.7.1 2.7.15`. Basically, it's trying to run a python that is not currently active via its shim (likely 3.6.7) in my case.

do you need to add: `self._remove_path(os.path.join(ASDF_DATA_DIR, "shims"))` ?

**Comment by techalchemy** [comment]
no it's just parsing your global file poorly...

**Comment by techalchemy** [comment]
@AlJohri can you give me the output of `ls -al ~/.asdf/.pyenv` and `~/.asdf/python/`?

**Comment by techalchemy** [comment]
ok i think the new version will work... if you dont mind, it would be helpful if you could try it out

**Comment by AlJohri** [comment]
sure, giving it a shot

**Comment by AlJohri** [comment]
I tried with the same installation command as above, from the PR branch.

with my global version set as before (`3.7.1 2.7.15`), I got:

```
Traceback (most recent call last):
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/bin/pyfinder", line 11, in <module>
    load_entry_point('pythonfinder', 'console_scripts', 'pyfinder')()
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/cli.py", line 33, in cli
    versions = [v for v in finder.find_all_python_versions()]
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 121, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict")
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 53, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 434, in create
    for p in _path_objects
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 434, in <dictcomp>
    for p in _path_objects
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 557, in create
    _new = cls(**creation_args)
  File "<attrs generated init 313b4fb5ec2257cb014a89624edb99c53f074594>", line 20, in __init__
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 513, in get_pythons
    for path, entry in self.children.items():
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 484, in children
    for child_key, child_val in self._gen_children():
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 477, in _gen_children
    yield (child.as_posix(), PathEntry.create(path=child, **pass_args))
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 557, in create
    _new = cls(**creation_args)
  File "<attrs generated init 313b4fb5ec2257cb014a89624edb99c53f074594>", line 16, in __init__
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 500, in get_py_version
    py_version = PythonVersion.from_path(path=self, name=self.name)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/python.py", line 418, in from_path
    instance_dict = cls.parse(py_version)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/python.py", line 366, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('No such command in 3.7.1 2.7.15 of python')>
```

in case it was related to that, I tried to set my global version to just one python (`3.7.1`) but I got the same error again:

```
Traceback (most recent call last):
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/bin/pyfinder", line 11, in <module>
    load_entry_point('pythonfinder', 'console_scripts', 'pyfinder')()
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/cli.py", line 33, in cli
    versions = [v for v in finder.find_all_python_versions()]
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 121, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict")
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 53, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 434, in create
    for p in _path_objects
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 434, in <dictcomp>
    for p in _path_objects
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 557, in create
    _new = cls(**creation_args)
  File "<attrs generated init 2665ebec158bcaee679ac71471c44977d17a6fac>", line 20, in __init__
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 513, in get_pythons
    for path, entry in self.children.items():
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/lib/python3.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 484, in children
    for child_key, child_val in self._gen_children():
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 477, in _gen_children
    yield (child.as_posix(), PathEntry.create(path=child, **pass_args))
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 557, in create
    _new = cls(**creation_args)
  File "<attrs generated init 2665ebec158bcaee679ac71471c44977d17a6fac>", line 16, in __init__
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/path.py", line 500, in get_py_version
    py_version = PythonVersion.from_path(path=self, name=self.name)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/python.py", line 418, in from_path
    instance_dict = cls.parse(py_version)
  File "/Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/src/pythonfinder/src/pythonfinder/models/python.py", line 366, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('No such command in 3.7.1 of python')>
```

If you've spent too much time on this @techalchemy and need to cut a release, I can debug this over the weekend for a follow up release?

**Comment by AlJohri** [comment]
Also, I set my global python to all three (`asdf global python 3.7.1 3.6.7 2.7.15`) and made it work:

```
python3: 3.7.1 (None) @ /Users/johria/.local/share/virtualenvs/newproject-pYEZLETE/bin/python3
python3: 3.7.1 (None) @ /Users/johria/.asdf/shims/python3
python: 3.7.1 (None) @ /Users/johria/.asdf/shims/python
python3.7m: 3.7.1 (None) @ /Users/johria/.asdf/shims/python3.7m
python3.7: 3.7.1 (None) @ /Users/johria/.asdf/shims/python3.7
python3: 3.7.1 (None) @ /usr/local/bin/python3
python3.7m: 3.7.1 (None) @ /usr/local/bin/python3.7m
python3.6: 3.6.7 (None) @ /Users/johria/.asdf/shims/python3.6
python3.6m: 3.6.7 (None) @ /Users/johria/.asdf/shims/python3.6m
python2: 2.7.15 (None) @ /Users/johria/.asdf/shims/python2
python2.7: 2.7.15 (None) @ /Users/johria/.asdf/shims/python2.7
python: 2.7.15 (None) @ /usr/local/bin/python
pythonw: 2.7.15 (None) @ /usr/local/bin/pythonw
python: 2.7.10 (None) @ /usr/bin/python
pythonw: 2.7.10 (None) @ /usr/bin/pythonw
python2.7: 2.7.10 (None) @ /usr/bin/python2.7
```

**Comment by AlJohri** [comment]
Note how all the pythons are pointing to shims instead of the true binaries though

**Comment by techalchemy** [comment]
What's interesting is:

```python
        py_version = get_python_version(path.path.absolute().as_posix())
        instance_dict = cls.parse(py_version.strip())
```

This code is failing in the error -- I just swapped it to turn the path into an absolute path -- but then it raises this:

```python
        if not isinstance(instance_dict.get("version"), Version) and not IGNORE_UNSUPPORTED:
            raise ValueError("Not a valid python path: %s" % path.path)
            return
```

What's weird is it literally shouuld invoke every python it encounters on your path.  I'm going to do two things -- remove the asdf shims and also double check the asdf version file -- is it actually located in `~/.tool-versions` or whatever? the function I'm using to parse it now is:

```python
def parse_asdf_version_order(filename=".tool-versions"):
    version_order_file = normalize_path(os.path.join("~", filename))
    if os.path.exists(version_order_file) and os.path.isfile(version_order_file):
        with io.open(version_order_file, encoding="utf-8") as fh:
            contents = fh.read()
        python_section = next(iter(
            line for line in contents.splitlines() if line.startswith("python")
        ), None)
        if python_section:
            python_key, versions = python_section.partition()
            if versions:
                return versions.split()
```

Which I've just realized has no variable expansion so that may be the issue, let me push up the changes and we can see if that helps

**Comment by techalchemy** [comment]
ok, branch pushed back up

**Comment by AlJohri** [comment]
just installed the latest pipenv via homebrew and it seems like it was unable to find my asdf pythons? no errors though!

![screen shot 2018-11-16 at 11 51 13 am](https://user-images.githubusercontent.com/2790092/48635390-000cb880-e996-11e8-92a0-b2e7715ad9cf.png)

```
$ pyfinder --version
pyfinder, version 1.1.9.post1
$ pyfinder --findall
python3: 3.7.1 (None) @ /usr/local/bin/python3
python3.7m: 3.7.1 (None) @ /usr/local/bin/python3.7m
python: 2.7.15 (None) @ /usr/local/bin/python
pythonw: 2.7.15 (None) @ /usr/local/bin/pythonw
python: 2.7.10 (None) @ /usr/bin/python
pythonw: 2.7.10 (None) @ /usr/bin/pythonw
python2.7: 2.7.10 (None) @ /usr/bin/python2.7
```

**Comment by AlJohri** [comment]
I think I know what might be the issue.... the env var name might be wrong. The README of asdf says `ASDF_DATA_DIR` but on my computer it is:

![screen shot 2018-11-16 at 11 58 14 am](https://user-images.githubusercontent.com/2790092/48635735-f768b200-e996-11e8-8016-47dd13b82809.png)

**Comment by AlJohri** [comment]
Yes! That worked!

```
$ export ASDF_DATA_DIR=$ASDF_DIR
$ pyfinder --findall
3.7.1: 3.7.1 (None) @ /Users/johria/.asdf/installs/python/3.7.1/bin/python3
3.7.1: 3.7.1 (None) @ /Users/johria/.asdf/installs/python/3.7.1/bin/python3.7m
python3: 3.7.1 (None) @ /usr/local/bin/python3
python3.7m: 3.7.1 (None) @ /usr/local/bin/python3.7m
3.6.7: 3.6.7 (None) @ /Users/johria/.asdf/installs/python/3.6.7/bin/python3
3.6.7: 3.6.7 (None) @ /Users/johria/.asdf/installs/python/3.6.7/bin/python3.6m
2.7.15: 2.7.15 (None) @ /Users/johria/.asdf/installs/python/2.7.15/bin/python
python: 2.7.15 (None) @ /usr/local/bin/python
pythonw: 2.7.15 (None) @ /usr/local/bin/pythonw
python: 2.7.10 (None) @ /usr/bin/python
pythonw: 2.7.10 (None) @ /usr/bin/pythonw
python2.7: 2.7.10 (None) @ /usr/bin/python2.7
```

I will track down what's the canonical name env var name here https://github.com/asdf-vm/asdf/issues/405

**Comment by AlJohri** [comment]
I got feedback from adsf on which env vars to rely on- I'll submit a PR with a fix.
