### ISSUE TITLE
Unable to install from git

### ISSUE THREAD

**Issue by svenpanne** [sarugaku/pythonfinder#44]
The commit 5715547c4528a415d8c22f54f36bf3504caeb3dc breaks installation of pythonfinder from git. Running `pyfinder --findall` terminates with:

```
Traceback (most recent call last):
  File "/home/sp/xx/.venv/bin/pyfinder", line 11, in <module>
    load_entry_point('pythonfinder', 'console_scripts', 'pyfinder')()
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/cli.py", line 33, in cli
    versions = [v for v in finder.find_all_python_versions()]
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/pythonfinder.py", line 136, in find_all_python_versions
    major=major, minor=minor, patch=patch, pre=pre, dev=dev, arch=arch, name=name
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 328, in find_all_python_versions
    values = list(self.get_pythons(sub_finder))
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 279, in get_pythons
    reverse=True
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 277, in <genexpr>
    (p for p in self._filter_paths(finder) if p.is_python),
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 264, in <genexpr>
    pth for pth in unnest(finder(p) for p in self.path_entries if p is not None)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/utils.py", line 150, in unnest
    for el in target:
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 264, in <genexpr>
    pth for pth in unnest(finder(p) for p in self.path_entries if p is not None)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/mixins.py", line 76, in find_all_python_versions
    path_filter = filter(None, (sub_finder(p) for p in self.children.values()))
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 501, in children
    for child_key, child_val in self._gen_children():
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 493, in _gen_children
    entry = PathEntry.create(path=child, **pass_args)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 574, in create
    _new = cls(**creation_args)
  File "<attrs generated init b2fd6775cdaa6b27d0fc0845b196e700ccaa616b>", line 16, in __init__
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/path.py", line 517, in get_py_version
    py_version = PythonVersion.from_path(path=self, name=self.name)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/models/python.py", line 431, in from_path
    py_version = get_python_version(path.path.absolute().as_posix())
  File "/home/sp/xx/.venv/local/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/home/sp/xx/.venv/src/pythonfinder/src/pythonfinder/utils.py", line 59, in get_python_version
    combine_stderr=False, write_to_stdout=False)
TypeError: run() got an unexpected keyword argument 'write_to_stdout'
```

The reason seems to be that the change https://github.com/sarugaku/vistir/commit/ce38a41f22483f87ef2ecb4ee5ed3f4101b1e614 is not yet in any released version of `visitr`. Releasing  a 0.25 version including that change to PyPI will probably fix that problem.

**Comment by jxltom** [comment]
Yeah, https://github.com/sarugaku/vistir/commit/ce38a41f22483f87ef2ecb4ee5ed3f4101b1e614 is introduced to fix bugs in pipenv. This won't be a problem after vistir is released.

**Comment by techalchemy** [comment]
The challenge of coordinating 5 package releases together :)
